from .didaskalia import Didaskalia
from .didask_tekst import DidaskTekst
from .kwestia import Kwestia
from .lista_osoba import ListaOsoba
from .lista_osob import ListaOsob
from .miejsce_czas import MiejsceCzas
from .naglowek_listy import NaglowekListy
from .naglowek_osoba import NaglowekOsoba
from .osoba import Osoba
