#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from librarian.book2anything import Book2Anything


class Book2Mobi(Book2Anything):
    format_name = "MOBI"
    ext = "mobi"
    uses_cover = True
    cover_optional = False
    uses_provider = True


if __name__ == '__main__':
    Book2Mobi.run()
