#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from librarian.book2anything import Book2Anything


class Book2Cover(Book2Anything):
    format_name = "JPEG"
    ext = "jpg"
    uses_cover = True
    cover_optional = False

    @staticmethod
    def transform(wldoc, cover):
        return wldoc.as_cover(cover_class=cover)


if __name__ == '__main__':
    Book2Cover.run()
