#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from librarian.book2anything import Book2Anything, Option
from librarian.parser import WLDocument


class Book2Txt(Book2Anything):
    format_name = "TXT"
    ext = "txt"
    uses_cover = False
    uses_provider = False
    parser_options = [
        Option('-i', '--ignore-dublin-core', dest='parse_dublincore', 
                action='store_false', default=True,
                help='don\'t try to parse dublin core metadata')
    ]
    transform_options = [
        Option('-w', '--wrap', action='store', type='int', dest='wrapping', default=0,
                help='set line wrap column')
    ]
    transform_flags = [
        Option('-r', '--raw', dest='raw-text', 
                action='store_true', default=False,
                help='Produce raw text, without any surrounding info.')
    ]
    transform = WLDocument.as_text


if __name__ == '__main__':
    Book2Txt.run()
