#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from librarian.book2anything import Book2Anything, Option


class Book2Mobi(Book2Anything):
    format_name = "MOBI"
    ext = "mobi"
    uses_cover = True
    cover_optional = False
    uses_provider = True

    transform_options = [
        Option('-k', '--use-kindlegen',
                action='store_true', dest='use_kindlegen', default=False,
                help='use kindlegen tool instead of Calibre')
        ]


if __name__ == '__main__':
    Book2Mobi.run()
