#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from librarian.book2anything import Book2Anything, Option
from librarian.formats.epub import EpubFormat


class Book2Epub(Book2Anything):
    format_cls = EpubFormat

if __name__ == '__main__':
    Book2Epub.run()
