#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from __future__ import unicode_literals

from librarian.book2anything import Book2Anything


class Book2Fb2(Book2Anything):
    format_name = "FB2"
    ext = "fb2"
    uses_cover = False
    uses_provider = True


if __name__ == '__main__':
    Book2Fb2.run()
