#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of Librarian, licensed under GNU Affero GPLv3 or later.
# Copyright © Fundacja Nowoczesna Polska. See NOTICE for more information.
#
from __future__ import unicode_literals

from librarian.book2anything import Book2Anything, Option


class Book2Html(Book2Anything):
    format_name = "HTML"
    ext = "html"
    uses_cover = False
    uses_provider = False
    transform_flags = [
        Option('-r', '--raw', dest='full-page',
                action='store_false', default=True,
                help='output raw text for use in templates')
    ]
    transform_options = [
        Option('--css', dest='css'),
        Option(
            '-b', '--base-url', dest='base_url', metavar='URL',
            help='specifies the base URL for relative image references'
        ),
    ]
    parser_options = [
        Option('-i', '--ignore-dublin-core', dest='parse_dublincore', 
                action='store_false', default=True,
                help='don\'t try to parse dublin core metadata')
    ]


if __name__ == '__main__':
    Book2Html.run()
